# Generated by Django 3.1.5 on 2021-01-30 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.TimeField()),
                ('estimated_delivery_time', models.TimeField()),
                ('delivery_address', models.CharField(max_length=600)),
                ('delivery_notes', models.CharField(max_length=600)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('status', models.ManyToManyField(through='api.OrderStatus', to='api.Status')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placed_orders',
            },
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='placed_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placedorder'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('comments', models.CharField(max_length=600)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.menuitem')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offer')),
                ('placed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placedorder')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
