# Generated by Django 3.1.5 on 2021-01-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210130_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='order_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
