# Generated by Django 3.1.7 on 2021-03-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210302_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='estimated_delivery_time',
            field=models.TimeField(null=True),
        ),
    ]
