# Generated by Django 3.1.7 on 2021-03-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210302_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='status',
        ),
        migrations.AddField(
            model_name='placedorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=models.SET('deleted status'), to='api.status'),
            preserve_default=False,
        ),
    ]
