# Generated by Django 3.1.7 on 2021-03-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='delivery_fees',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
