# Generated by Django 3.1.7 on 2021-03-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_area_delivery_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='complete',
        ),
    ]
