# Generated by Django 3.1.7 on 2021-03-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210308_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='status',
            field=models.ForeignKey(null=True, on_delete=models.SET('deleted status'), to='api.status'),
        ),
    ]
