# Generated by Django 3.1.7 on 2021-03-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210308_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='comments',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
