from .models import Customer
from .models import Area
from .models import Address
from .models import Task
from .models import Category
from .models import Size
from .models import MenuItem
from .models import MenuItemSize
from .models import Offer
from .models import Status
from .models import PlacedOrder
from .models import OrderItem
