from .serializers import UserSerializer
from .serializers import GroupSerializer
from .serializers import CategorySerializer
from .serializers import MenuItemSizeSerializer
from .serializers import SizeSerializer
from .serializers import MenuItemSerializer
from .serializers import OfferSerializer
from .serializers import OrderItemSerializer
from .serializers import PlacedOrderSerializer
from .serializers import StatusSerializer
from .serializers import CustomerSerializer
from .serializers import AreaSerializer
from .serializers import AddressSerializer
